name: TorchAO Float8

on:
  push:
    branches:
      - main
    paths:
      - 'torchao_float8/**'
      - 'common_utils/**'
      - '.github/workflows/build-torchao-float8.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'torchao_float8/**'
      - 'common_utils/**'
      - '.github/workflows/build-torchao-float8.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest

      - name: cleanup space on github vm
        run: |
          rm -rf /usr/share/dotnet \
                /opt/ghc \
                "$AGENT_TOOLSDIRECTORY"
      
          docker system prune -af || true
          df -h

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: torchao_float8/Dockerfile
          push: false
          tags: torchao-float8:latest

      - name: Test Docker image
        run: |
          docker run --rm torchao-float8:latest uv --version
          docker run --rm torchao-float8:latest python3.12 --version

      - name: Clean up Docker resources
        if: always()
        run: |
          docker system prune -af --volumes
          df -h